# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztJF9rpWfOQJb7t2ZHeqznz3iz9JC-4t
"""

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score
import time

dftrain = pd.read_csv('/content/MNIST_train.csv')
dfval = pd.read_csv('/content/MNIST_validation.csv')

dftrain = dftrain.drop('even', axis=1)

dfval = dfval.drop('even', axis=1)

featurecols = list(dftrain.columns)
targetcol = 'label'
featurecols.remove(targetcol)

print('length of featurecolumns is', len(featurecols))

Xtrain = np.array(dftrain[featurecols]) / 255
ytrain = np.array(dftrain[targetcol])

Xval = np.array(dfval[featurecols]) / 255
yval = np.array(dfval[targetcol])

class PCAModel:
    def __init__(self, n_components):
        self.n_components = n_components
        self.mean = None
        self.components = None
        self.explained_variance = None

    def fit(self, X):
        X = np.array(X, dtype=float)

        self.mean = np.mean(X, axis=0)
        X_centered = X - self.mean

        cov_matrix = np.cov(X_centered, rowvar=False)
        eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)

        sorted_idx = np.argsort(eigenvalues)[::-1]

        self.explained_variance = eigenvalues[sorted_idx][:self.n_components]
        self.components = eigenvectors[:, sorted_idx][:, :self.n_components]

    def predict(self, X):
        if self.mean is None:
            raise ValueError("PCA is not fitted yet.")

        X_centered = X - self.mean
        return np.dot(X_centered, self.components)

    def reconstruct(self, X):
        Z = self.predict(X)
        return np.dot(Z, self.components.T) + self.mean

class KNNClassifier:
    def __init__(self, k=5):
        self.k = k
        self.X_train = None
        self.y_train = None

    def fit(self, X, y):
        self.X_train = np.array(X)
        self.y_train = np.array(y)

    def predict(self, X):
        X = np.array(X)
        y_pred = []
        for x in X:
            distances = np.linalg.norm(self.X_train - x, axis=1)
            nn_idx = np.argsort(distances)[:self.k]
            nn_labels = self.y_train[nn_idx]
            counts = np.bincount(nn_labels)
            y_pred.append(np.argmax(counts))
        return np.array(y_pred)

pca = PCAModel(n_components=100)
pca.fit(Xtrain)
X_train_pca = pca.predict(Xtrain)
X_val_pca = pca.predict(Xval)

print(f"Shape after PCA: {X_train_pca.shape}")
knn = KNNClassifier(k=5)
start_time = time.time()
knn.fit(X_train_pca, ytrain)
y_train_pred = knn.predict(X_train_pca)
y_val_pred = knn.predict(X_val_pca)
training_time = time.time() - start_time
train_acc = accuracy_score(ytrain, y_train_pred)
val_acc = accuracy_score(yval, y_val_pred)
train_f1 = f1_score(ytrain, y_train_pred, average='weighted')
val_f1 = f1_score(yval, y_val_pred, average='weighted')

print("----------------------------")
print("KNN + PCA ")
print("----------------------------")
print(f"Train Accuracy: {train_acc:.4f}")
print(f"Validation Accuracy: {val_acc:.4f}")
print(f"Train F1: {train_f1:.4f}")
print(f"Validation F1: {val_f1:.4f}")
print(f"Training + Prediction time: {training_time:.2f} seconds")

"""Hyperparameters tuning"""

pca_k = PCAModel(n_components=100)
pca_k.fit(Xtrain)
X_train_pca_k = pca.predict(Xtrain)
X_val_pca_k = pca.predict(Xval)

print(f"Shape after PCA: {X_train_pca_k.shape}")

k_vals = [3, 5, 10, 20, 30]

for k in k_vals:
    knn_k = KNNClassifier(k=k)
    start_time_k = time.time()

    knn_k.fit(X_train_pca_k, ytrain)

    y_train_pred_k = knn_k.predict(X_train_pca_k)
    y_val_pred_k = knn_k.predict(X_val_pca_k)

    training_time_k = time.time() - start_time_k

    train_acc_k = accuracy_score(ytrain, y_train_pred_k)
    val_acc_k = accuracy_score(yval, y_val_pred_k)
    train_f1_k = f1_score(ytrain, y_train_pred_k, average='weighted')
    val_f1_k = f1_score(yval, y_val_pred_k, average='weighted')

    print("----------------------------")
    print(f"KNN (k={k}) + PCA ")
    print("----------------------------")
    print(f"Train Accuracy: {train_acc_k:.4f}")
    print(f"Validation Accuracy: {val_acc_k:.4f}")
    print(f"Train F1: {train_f1_k:.4f}")
    print(f"Validation F1: {val_f1_k:.4f}")
    print(f"Training + Prediction time: {training_time_k:.2f} seconds")

components = [784, 600, 500, 400, 300, 200, 100]

for c in components:
    n_components_c = c
    pca_c = PCAModel(n_components=n_components_c)
    pca_c.fit(Xtrain)
    X_train_pca_c = pca_c.predict(Xtrain)
    X_val_pca_c = pca_c.predict(Xval)

    print(f"Shape after PCA: {X_train_pca_c.shape}")

    k_c = 5
    knn_c = KNNClassifier(k=k_c)
    start_time_c = time.time()

    knn_c.fit(X_train_pca_c, ytrain)

    y_train_pred_c = knn_c.predict(X_train_pca_c)
    y_val_pred_c = knn_c.predict(X_val_pca_c)

    training_time_c = time.time() - start_time_c

    train_acc_c = accuracy_score(ytrain, y_train_pred_c)
    val_acc_c = accuracy_score(yval, y_val_pred_c)
    train_f1_c = f1_score(ytrain, y_train_pred_c, average='weighted')
    val_f1_c = f1_score(yval, y_val_pred_c, average='weighted')

    print("----------------------------")
    print(f"KNN (k={k_c}) + PCA (components={n_components_c})")
    print("----------------------------")
    print(f"Train Accuracy: {train_acc_c:.4f}")
    print(f"Validation Accuracy: {val_acc_c:.4f}")
    print(f"Train F1: {train_f1_c:.4f}")
    print(f"Validation F1: {val_f1_c:.4f}")
    print(f"Training + Prediction time: {training_time_c:.2f} seconds")

n_components_best = 100
pca_best = PCAModel(n_components=n_components_c)
pca_best.fit(Xtrain)
X_train_pca_best = pca_best.predict(Xtrain)
X_val_pca_best = pca_best.predict(Xval)

print(f"Shape after PCA: {X_train_pca_best.shape}")

k_best = 5
knn_best = KNNClassifier(k=k_best)
start_time_best = time.time()

knn_best.fit(X_train_pca_best, ytrain)

y_train_pred_best = knn_best.predict(X_train_pca_best)
y_val_pred_best = knn_best.predict(X_val_pca_best)

training_time_best = time.time() - start_time_best

train_acc_best = accuracy_score(ytrain, y_train_pred_best)
val_acc_best = accuracy_score(yval, y_val_pred_best)
train_f1_best = f1_score(ytrain, y_train_pred_best, average='weighted')
val_f1_best = f1_score(yval, y_val_pred_best, average='weighted')

print("----------------------------")
print(f"KNN (k={k_best}) + PCA (components={n_components_best})")
print("----------------------------")
print(f"Train Accuracy: {train_acc_best:.4f}")
print(f"Validation Accuracy: {val_acc_best:.4f}")
print(f"Train F1: {train_f1_best:.4f}")
print(f"Validation F1: {val_f1_best:.4f}")
print(f"Training + Prediction time: {training_time_best:.2f} seconds")